name: CI/CD Pipeline

on: 
 push:
   branches : ['main']
 pull_request:
   branches: ['main']

env:
  NODE_VERSION : 18.x #match your project's Node version

jobs:
    build-and-test:
     runs-on: ubuntu-laest

     steps:
     - name: Checkout code 
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: ${{env.NODE_VERSION}}
         cache: 'npm'

     - name: Install dependencies
       run: npm ci #clean install for reliability 

     - name: Run tests
       run: npm test # make sure you have test scripts!

     - name: Build project 
       run: npm run build # Required for React/vite projects
