name: Scheduled Checks
on:
  schedule:
    - cron: '0 0 * * 1-5' # Midnight UTC, mon-fri
  workflow_dispatch: # Allow manual triggers

env:
  NODE_VERSION: 18.x
  
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci


      - name: Run health Checks
        run: npm test -- --watchAll=false

      - name: Notify status
        run: echo "Schedule checks completed at $(date)"
    